import Vue from 'vue'
import Vuex from 'vuex'
import * as firebase from 'firebase'

Vue.use(Vuex)

export const store = new Vuex.Store({
  state: {
    loadedCompetitions: [
      {
        imageUrl: 'http://www.etonline.com/sites/default/files/images/2016-04/1280_cirque_du_soleil_ovo.jpg',
        id: 'america-youth-on-parade',
        title: 'America Youth On Parade',
        date: new Date(),
        description: 'An awesome baton competition!',
        location: 'South Bend, IN'
      },
      {
        imageUrl: 'https://www.billboard.com/files/media/09-Cirque-du-Soleils-SEP7IMO-DIA-press-2017-billboard-1548.jpg',
        id: 'congressional-cup-weekend',
        title: 'Congressional Cup Weekend',
        date: new Date(),
        description: 'An awesome baton competition!',
        location: 'Harrisburg, VA'
      },
      {
        imageUrl: 'https://leeds-list.com/wp-content/uploads/2016/12/cirque-du-soleil-dec-2016-no-credit.jpg',
        id: 'twirl-mania',
        title: 'Twirl Mania',
        date: new Date(),
        description: 'An awesome baton competition!',
        location: 'Orlando, FL'
      }
    ],
    user: null,
    loading: false,
    error: null
  },
  mutations: {
    registerUserForCompetition (state, payload) {
      const id = payload.id
      if (state.user.registeredCompetitions.findIndex(competition => competition.id === id) >= 0) {
        return 0
      }
      state.user.registeredCompetitions.push(id)
      // id = competitionID, fbKey = key generated by firebase
      state.user.fbKeys[id] = payload.fbKey
    },
    unregisterUserFromCompetition (state, payload) {
      const registeredCompetitions = state.user.registeredCompetitions
      registeredCompetitions.splice(registeredCompetitions.findIndex(competition => competition.id === payload), 1)
      Reflect.deleteProperty(state.user.fbKeys, payload)
    },
    setLoadedCompetitions (state, payload) {
      state.loadedCompetitions = payload
    },
    createCompetition (state, payload) {
      state.loadedCompetitions.push(payload)
    },
    updateCompetitionData (state, payload) {
      const competition = state.loadedCompetitions.find(competition => {
        return competition.id === payload.id
      })
      if (payload.title) {
        competition.title = payload.title
      }
      if (payload.description) {
        competition.description = payload.description
      }
      if (payload.date) {
        competition.date = payload.date
      }
    },
    setUser (state, payload) {
      state.user = payload
    },
    setLoading (state, payload) {
      state.loading = payload
    },
    setError (state, payload) {
      state.error = payload
    },
    clearError (state) {
      state.error = null
    }
  },
  actions: {
    registerUserForCompetition ({commit, getters}, payload) {
      commit('setLoading', true)
      const user = getters.user
      firebase.database().ref('/users/' + user.id).child('/registeredCompetitions/')
      .push(payload)
      .then(data => {
        commit('setLoading', false)
        commit('registerUserForCompetition', {id: payload, fbKey: data.key})
      })
      .catch(error => {
        console.log(error)
        commit('setLoading', false)
      })
    },
    unregisterUserFromCompetition ({commit, getters}, payload) {
      commit('setLoading', true)
      const user = getters.user
      if (!user.fbKeys) {
        return
      }
      const fbKey = user.fbKeys[payload]
      firebase.database().ref('/users/' + user.id + '/registeredCompetitions/').child(fbKey)
      .remove()
      .then(() => {
        commit('setLoading', false)
        commit('unregisterUserFromCompetition', payload)
      })
      .catch(error => {
        console.log(error)
        commit('setLoading', false)
      })
    },
    loadCompetitions ({commit}) {
      commit('setLoading', true)
      firebase.database().ref('competitions').once('value')
        .then((data) => {
          const competitions = []
          const obj = data.val()
          for (let key in obj) {
            competitions.push({
              id: key,
              title: obj[key].title,
              description: obj[key].description,
              imageUrl: obj[key].imageUrl,
              date: obj[key].date,
              location: obj[key].location,
              creatorId: obj[key].creatorId
            })
          }
          commit('setLoadedCompetitions', competitions)
          commit('setLoading', false)
        }
        )
        .catch(
          (error) => {
            console.log(error)
            commit('setLoading', false)
          }
        )
    },
    createCompetition ({commit, getters}, payload) {
      const competition = {
        title: payload.title,
        location: payload.location,
        description: payload.description,
        date: payload.date.toISOString(),
        creatorId: getters.user.id
      }
      let imageUrl
      let key
      firebase.database().ref('competitions').push(competition)
      .then((data) => {
        key = data.key
        console.log('Success! ', data)
        return key
      })
      .then(key => {
        const filename = payload.image.name
        const ext = filename.slice(filename.lastIndexOf('.'))
        return firebase.storage().ref('competitions/' + key + '.' + ext).put(payload.image)
      })
      .then(fileData => {
        imageUrl = fileData.metadata.downloadURLs[0]
        return firebase.database().ref('competitions').child(key).update({imageUrl: imageUrl})
      })
      .then(() => {
        commit('createCompetition', {
          ...competition,
          imageUrl: imageUrl,
          id: key
        })
      })
      .catch((error) => {
        console.log('Error: ', error)
      })
      // Reach out to Firebase and store it
    },
    updateCompetitionData ({commit}, payload) {
      commit('setLoading', true)
      const updateObj = {}
      if (payload.title) {
        updateObj.title = payload.title
      }
      if (payload.description) {
        updateObj.description = payload.description
      }
      if (payload.date) {
        updateObj.date = payload.date
      }
      firebase.database().ref('competitions').child(payload.id).update(updateObj)
        .then(() => {
          commit('setLoading', false)
          commit('updateCompetitionData', payload)
        })
        .catch(error => {
          console.log(error)
          commit('setLoading', false)
        })
    },
    signUserUp ({commit}, payload) {
      commit('setLoading', true)
      commit('clearError')
      firebase.auth().createUserWithEmailAndPassword(payload.email, payload.password)
      .then(
        user => {
          commit('setLoading', false)
          const newUser = {
            id: user.uid,
            registeredCompetitions: [],
            firstName: '',
            lastName: payload.lastName,
            birthday: payload.birthday,
            fbKeys: {}
          }
          commit('setUser', newUser)
        }
      )
      .catch(
        error => {
          commit('setLoading', false)
          commit('setError', error)
          console.log(error)
        }
      )
    },
    signUserIn ({commit}, payload) {
      commit('setLoading', true)
      commit('clearError')
      firebase.auth().signInWithEmailAndPassword(payload.email, payload.password)
      .then(
        user => {
          commit('setLoading', false)
          const returningUser = {
            id: user.uid,
            registeredCompetitions: [],
            firstName: '',
            lastName: user.lastName,
            birthday: user.birthday,
            fbKeys: {}
          }
          commit('setUser', returningUser)
        }
      )
      .catch(
        error => {
          commit('setLoading', false)
          commit('setError', error)
          console.log(error)
        }
      )
    },
    clearError ({commit}) {
      commit('clearError')
    },
    autoSignIn ({commit}, payload) {
      commit('setUser', {id: payload.uid,
        registeredCompetitions: [],
        fbKeys: {}
      })
    },
    fetchUserData ({commit, getters}) {
      commit('setLoading', true)
      firebase.database().ref('/users/' + getters.user.id + '/registeredCompetitions/').once('value')
      .then(data => {
        const dataPairs = data.val()
        let registeredCompetitions = []
        let swappedPairs = {}
        for (let key in dataPairs) {
          registeredCompetitions.push(dataPairs[key])
          swappedPairs[dataPairs[key]] = key
        }
        const udpatedUser = {
          id: getters.user.id,
          registeredCompetitions: registeredCompetitions,
          fbKeys: swappedPairs
        }
        commit('setLoading', false)
        commit('setUser', updatedUser)
      })
      .catch(error => {
        console.log(error)
        commit('setLoading', false)
      })
    },
    logout ({commit}) {
      firebase.auth().signOut()
      commit('setUser', null)
    }
  },
  getters: {
    loadedCompetitions (state) {
      return state.loadedCompetitions.sort((a, b) => {
        return a.date > b.date
      })
    },
    loadedCompetition (state) {
      return (competitionid) => {
        return state.loadedCompetitions.find((competition) => {
          return competition.id === competitionid
        })
      }
    },
    featuredCompetitions (state, getters) {
      return getters.loadedCompetitions.slice(0, 2)
    },
    user (state) {
      return state.user
    },
    loading (state) {
      return state.loading
    },
    error (state) {
      return state.error
    }
  }
})
